version: '3'

services:

# MongoDB
   mongo-db:
     image: mongo:4.4
     restart: always
     command: --nojournal
     hostname: mongo-db
     container_name: mongo-db
     ports:
       - "27017:27017"
     volumes:
       - db-data:/data/db

# Orion
   orion:
     image: fiware/orion:3.11.0
     restart: always
     hostname: orion
     container_name: orion
     depends_on:
       - mongo-db
     ports:
       - "1026:1026"
     command: -dbhost mongo-db -corsOrigin __ALL -corsMaxAge 600

# STH Comet
   fiware-sth-comet:
     image: telefonicaiot/fiware-sth-comet
     restart: always
     hostname: sth-comet
     container_name: sth-comet
     depends_on:
       - mongo-db
     ports:
       - "8666:8666"
     environment:
       - STH_HOST=0.0.0.0
       - STH_PORT=8666
       - DB_PREFIX=sth_
       - DB_URI=mongo-db:27017
       - LOGOPS_LEVEL=DEBUG

# Mosquitto
   mosquitto:
     image: eclipse-mosquitto:latest
     restart: always
     hostname: mosquitto
     command: mosquitto -c /mosquitto-no-auth.conf
     container_name: mosquitto
     expose:
       - "1883"
       - "9001"
     ports:
       - "1883:1883"
       - "9001:9001"
     volumes:
       - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

# IoT Agent
   iot-agent:
     image: fiware/iotagent-ul:latest
     restart: always
     hostname: iot-agent
     container_name: iot-agent
     depends_on:
       - mongo-db
       - mosquitto
     expose:
       - "4041"
     ports:
       - "4041:4041"
     environment:
       - IOTA_CB_HOST=orion
       - IOTA_CB_PORT=1026
       - IOTA_NORTH_PORT=4041
       - IOTA_REGISTRY_TYPE=mongodb
       - IOTA_LOG_LEVEL=DEBUG
       - IOTA_TIMESTAMP=true
       - IOTA_CB_NGSI_VERSION=v2
       - IOTA_AUTOCAST=true
       - IOTA_MONGO_HOST=mongo-db
       - IOTA_MONGO_PORT=27017
       - IOTA_MONGO_DB=iotagentul
       - IOTA_PROVIDER_URL=http://iot-agent:4041
       - IOTA_MQTT_HOST=mosquitto
       - IOTA_MQTT_PORT=1883

volumes:
   db-data:
  
